# Generated by Django 5.2.7 on 2025-10-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformationStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siswa_aktif', models.IntegerField(default=0)),
                ('guru_profesional', models.IntegerField(default=0)),
                ('program_keahlian', models.IntegerField(default=0)),
            ],
        ),
    ]
