# Generated by Django 5.2.7 on 2025-10-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('nama_kaprog', models.CharField(max_length=100)),
                ('jumlah_siswa', models.IntegerField(default=0)),
                ('jumlah_guru', models.IntegerField(default=0)),
            ],
        ),
    ]
