# Generated by Django 5.2.7 on 2025-10-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_berita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
